[init]
defaultBranch = main

[status]
short = true
branch = true

[core]
editor = nvim
pager = delta

[user]
name = Mads Bram Cordes
email = Mobilpadde@gmail.com
username = Mobilpadde

[alias]
who = shortlog -s --
save = stash save -u
pop = stash pop
lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative --all

[push]
default = upstream
followTags = true

[pull]
rebase = false

[merge]
conflictstyle = diff3

[diff]
colormoved = default
colormovedws = allow-indentation-change

# delta
[interactive]
diffFilter = delta --color-only

[delta]
features = decorations zebra-dark
line-numbers = true
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
