[init]
  defaultBranch = main

[user]
	name = Mads Bram Cordes
  email = Mobilpadde@gmail.com
  username = Mobilpadde

[alias]
  who = shortlog -s --
  save = stash save -u
  pop = stash pop
  lg = log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative --all

[push]
  default = upstream

[core]
	editor = vim
  pager = delta

[merge]
  conflictstyle = diff3

[diff]
  colorMoved = default

# delta
[interactive]
  diffFilter = delta --color-only

[delta]
  line-numbers = true
  features = decorations zebra-dark
